version: '3.9'

services:
  # nestapp:
  #   container_name: nestapp
  #   image: ahmadghazadeh/nestapp:1.0.0
  #   build:
  #    context: .
  #    dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - DB_TYPE=protgres
  #     - PG_HOST=progresDB
  #     - PG_USER=postgres
  #     - PG_PASSWORD=postgres
  #     - PG_DATABASE=postgres
  #     - PG_PORT=5432
  #   depends_on:
  #     - progresDB
  progresDB:
    container_name: progresDB
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pgdata:/var/lib/postgresql/POSTGRES_DATABASE
volumes:
  pgdata: {}


    

    